### ISSUE TITLE
Question about layers of this model

### ISSUE THREAD

**Issue by lygztq** [cszhangzhen/HGP-SL#7]
Hi, your paper is really an interesting work!
However I have two questions about the layers used in your model

1. I find that you use both the `GCNConv` and another new-defined `GCN` in your network. Is there any difference between these two layers?
2. I'm confused when reading your code in `NodeInformationScore`. I think you use the random walk version of Laplacian (i.e. the `I - D^{-1}A` ) in your paper. However in the `NodeInformationScore` implementation you use the symmetric version (i.e. the `I - D^{-1/2}AD^{-1/2}`). Also, I personally find the implementation has some problems. The `edge_weight` after `add_remaining_self_loops` will have self-loops, thus the final result of the `norm` function is `I - D^{-1/2}(A+I)D^{-1/2} = - D^{-1/2}AD^{-1/2}` instead of the `I - D^{-1/2}AD^{-1/2}`.

**Comment by cszhangzhen** [comment]
Hi, Thanks for your interest in our work!

Here are my  answers:

A1, We remove the adding self-loops operation in our new-defined ```GCN``` module, since the structure learning module has already taken self-loops into consideration. The original ```GCNConv``` is used only in the first layer and we add self-loops manually like GCN paper described.

A2, Yes, you are right. We actually use the symmetric version of ```(i.e. the I - \tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2})``` in NodeInformationScore.

However, your analysis is not correct.

> The edge_weight after add_remaining_self_loops will have self-loops, thus the final result of the norm function is I - D^{-1/2}(A+I)D^{-1/2} = - D^{-1/2}AD^{-1/2} instead of the I - D^{-1/2}AD^{-1/2}.

After structure learning module, it has automatically learned the self-loops, ```i.e., \tilde{A} ≠ A  + I  and \tilde{D}_{ii} = \sum_{i} \tilde{A}_{ij}```, and each node has different self-loop values. Therefore, ``` - D^{-1/2}(A+I)D^{-1/2} ≠ - D^{-1/2}AD^{-1/2}```. Also, note that for ``` edge_weight```, we use ```add_remaining_self_loops``` to **fill zeros instead of ones**, which make the ```edge_index``` be consistent with the learned structure information.

**Comment by lygztq** [comment]
Thanks! Now I understand how your `NodeInformationScore` works.
